# alembic.ini
#run locally as follows:
#> $env:DATABASE_URL = "postgresql+psycopg://drsynth:drsynth@localhost:5432/drsynth"
#> alembic upgrade head
[alembic]
# Path (relative or absolute) to your migrations env + versions.
# If we did `alembic init migrations`, this will match that.
script_location = migrations

# Optional, but useful so Alembic can find your code if needed
prepend_sys_path = .

# -- Logging config below is mostly boilerplate -----------------

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
