name: drsynth
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.13.5
  # GPU stack (Windows / NVIDIA)
  # Numeric libs w/ wheels so we avoid builds
  - numpy
  - scipy
  # Audio I/O
  - libsndfile
  - pip
  - pip:
      - pyannote.audio
      - faster-whisper==1.*
      - sounddevice
      - soundfile
      - omegaconf
# pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
# pip install torchcodec
# conda install anaconda::ffmpeg
# pip install --only-binary=:all: "scikit-learn>=1.6,<1.7"
# pip install PyAudioWPatch
# pip install "grpcio-tools>=1.62" protobuf
# pip install pydantic>=2.8
# pip install confluent-kafka>=2.
# pip install protobuf>=5.29
# pip install fastapi>=0.115
# pip install uvicorn[standard]>=0.30