{{- if .Values.rtservice.hfToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drsynth-stack.fullname" . }}-secrets
  labels:
    {{- include "drsynth-stack.labels" . | nindent 4 }}
type: Opaque
data:
  HF_TOKEN: {{ .Values.rtservice.hfToken | b64enc | quote }}
{{- end }}
