# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import speech_provider_pb2 as speech__provider__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in speech_provider_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpeechProviderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCapabilities = channel.unary_unary(
                '/nanosamurai.speech.v1.SpeechProvider/GetCapabilities',
                request_serializer=speech__provider__pb2.CapabilitiesRequest.SerializeToString,
                response_deserializer=speech__provider__pb2.CapabilitiesResponse.FromString,
                _registered_method=True)
        self.TranscribeWindow = channel.unary_unary(
                '/nanosamurai.speech.v1.SpeechProvider/TranscribeWindow',
                request_serializer=speech__provider__pb2.TranscribeWindowRequest.SerializeToString,
                response_deserializer=speech__provider__pb2.TranscribeWindowResponse.FromString,
                _registered_method=True)
        self.StreamTranscribe = channel.stream_stream(
                '/nanosamurai.speech.v1.SpeechProvider/StreamTranscribe',
                request_serializer=speech__provider__pb2.ProviderAudioFrame.SerializeToString,
                response_deserializer=speech__provider__pb2.ProviderTranscriptEvent.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/nanosamurai.speech.v1.SpeechProvider/Health',
                request_serializer=speech__provider__pb2.HealthRequest.SerializeToString,
                response_deserializer=speech__provider__pb2.HealthResponse.FromString,
                _registered_method=True)


class SpeechProviderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranscribeWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTranscribe(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeechProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=speech__provider__pb2.CapabilitiesRequest.FromString,
                    response_serializer=speech__provider__pb2.CapabilitiesResponse.SerializeToString,
            ),
            'TranscribeWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.TranscribeWindow,
                    request_deserializer=speech__provider__pb2.TranscribeWindowRequest.FromString,
                    response_serializer=speech__provider__pb2.TranscribeWindowResponse.SerializeToString,
            ),
            'StreamTranscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTranscribe,
                    request_deserializer=speech__provider__pb2.ProviderAudioFrame.FromString,
                    response_serializer=speech__provider__pb2.ProviderTranscriptEvent.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=speech__provider__pb2.HealthRequest.FromString,
                    response_serializer=speech__provider__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nanosamurai.speech.v1.SpeechProvider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nanosamurai.speech.v1.SpeechProvider', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpeechProvider(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanosamurai.speech.v1.SpeechProvider/GetCapabilities',
            speech__provider__pb2.CapabilitiesRequest.SerializeToString,
            speech__provider__pb2.CapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranscribeWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanosamurai.speech.v1.SpeechProvider/TranscribeWindow',
            speech__provider__pb2.TranscribeWindowRequest.SerializeToString,
            speech__provider__pb2.TranscribeWindowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTranscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/nanosamurai.speech.v1.SpeechProvider/StreamTranscribe',
            speech__provider__pb2.ProviderAudioFrame.SerializeToString,
            speech__provider__pb2.ProviderTranscriptEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nanosamurai.speech.v1.SpeechProvider/Health',
            speech__provider__pb2.HealthRequest.SerializeToString,
            speech__provider__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
