{{- if and .Values.hfCache.enabled .Values.hfCache.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nanosamurai-stack.fullname" . }}-hf-cache-pvc
  labels:
    {{- include "nanosamurai-stack.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.hfCache.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.hfCache.pvc.size | quote }}
  {{- if .Values.hfCache.pvc.storageClassName }}
  storageClassName: {{ .Values.hfCache.pvc.storageClassName | quote }}
  {{- end }}
{{- end }}
