{{- if .Values.recordings.hostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nanosamurai-stack.fullname" . }}-recordings-pv
  labels:
    {{- include "nanosamurai-stack.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: {{ .Values.recordings.hostPath | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nanosamurai-stack.fullname" . }}-recordings-pvc
  labels:
    {{- include "nanosamurai-stack.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: {{ include "nanosamurai-stack.fullname" . }}-recordings-pv
  storageClassName: ""
{{- else if .Values.recordings.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nanosamurai-stack.fullname" . }}-recordings-pvc
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "nanosamurai-stack.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.recordings.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.recordings.pvc.size | quote }}
  {{- if .Values.recordings.pvc.storageClassName }}
  storageClassName: {{ .Values.recordings.pvc.storageClassName | quote }}
  {{- end }}
{{- end -}}
